export function calculate(kind:string,v:Record<string,number>){
 const positive=(...keys:string[])=>keys.forEach(k=>{if(!Number.isFinite(v[k])||v[k]<=0)throw Error(`${k}: informe um valor maior que zero.`)});
 const f=(n:number)=>n.toLocaleString('pt-BR',{maximumFractionDigits:3});
 if(kind==='Potência e corrente'){positive('P','U','η','FP');if(v['η']>1||v.FP>1)throw Error('Rendimento e FP devem estar entre 0 e 1.');const p=v.P/v['η'],s=p/v.FP;return {formula:'Pentrada = Peixo / η; I = Peixo × 1000 / (√3 × U × η × FP); S = Pentrada / FP; Q = √(S² − Pentrada²)',sub:`I = ${v.P} × 1000 / (√3 × ${v.U} × ${v['η']} × ${v.FP})`,result:`${f(s*1000/(Math.sqrt(3)*v.U))} A`,details:`Entrada: ${f(p)} kW · Aparente: ${f(s)} kVA · Reativa: ${f(Math.sqrt(Math.max(0,s*s-p*p)))} kvar`,limit:'Motor trifásico equilibrado, regime senoidal. P é potência mecânica no eixo. Estimativa não substitui corrente de placa.'};}
 if(kind==='Velocidade'){positive('f','polos');if(v.polos%2||v.n<0||v.n>120*v.f/v.polos||!Number.isFinite(v.n))throw Error('Use polos pares e rotação entre 0 e a velocidade síncrona.');const ns=120*v.f/v.polos;return {formula:'ns = 120 × f / polos; s = (ns − n) / ns × 100',sub:`ns = 120 × ${v.f} / ${v.polos}`,result:`${f(ns)} rpm`,details:`Escorregamento: ${f((ns-v.n)/ns*100)}%`,limit:'Modelo de motor de indução em operação motora; não contempla regeneração.'};}
 if(kind==='Compensada'){positive('U','Id','k');if(v.k>1)throw Error('k deve ser maior que zero e no máximo 1.');return {formula:'Um = k × Un; Im ≈ k × Id; Irede ≈ k² × Id; T/Tdireta ≈ k²',sub:`Irede = ${v.k}² × ${v.Id}`,result:`${f(v.k*v.k*v.Id)} A na rede`,details:`Motor: ${f(v.k*v.Id)} A · Tensão: ${f(v.k*v.U)} V · Torque: ${f(v.k*v.k*100)}% da partida direta`,limit:'Autotransformador ideal e comparação à mesma velocidade. Não dimensiona contatores ou proteções.'};}
 if(kind==='Estrela-triângulo'){positive('U','Id');return {formula:'Ufase,Y = Ulinha / √3; Ilinha,Y ≈ Idireta,Δ / 3; TY ≈ TΔ / 3',sub:`IY = ${v.Id} / 3`,result:`${f(v.Id/3)} A em estrela`,details:`Tensão por enrolamento: ${f(v.U/Math.sqrt(3))} V · Torque: 33,33% do torque em partida direta Δ`,limit:'Somente motor com seis terminais acessíveis e tensão nominal em Δ igual à rede; mesma velocidade e impedância idealizada.'};}
 positive('valor');const w=v.valor*(v.unidade===1?735.49875:v.unidade===2?745.699872:1000);return {formula:'1 cv = 735,49875 W; 1 hp = 745,699872 W; 1 kW = 1000 W',sub:`Conversão do valor ${v.valor}`,result:`${f(w/1000)} kW`,details:`${f(w/735.49875)} cv · ${f(w/745.699872)} hp · ${f(w)} W`,limit:'cv (cavalo-vapor métrico) e hp mecânico são unidades diferentes.'};
}
