export const tracks=['Fundamentos e segurança','Partidas convencionais','Acionamentos eletrônicos','Aplicação e diagnóstico'];
export const criteria=['Interpretação técnica','Planejamento','Cálculos','Organização da execução','Verificações de segurança','Testes e diagnóstico','Documentação','Trabalho em equipe'];
const raw=[
['Reconhecimento de componentes',0,'Uma oficina precisa identificar os dispositivos de um painel antes de atualizar sua documentação.','Considere QF (disjuntor), KM (contator), FR (relé de sobrecarga), S0 (botoeira NF), S1 (botoeira NA) e H1 (sinalizador). Comando didático em 24 Vcc.','Associe cada identificação à função; diferencie proteção contra curto-circuito e sobrecarga; explique por que o contator não substitui a proteção.','Tabela com seis componentes, função, símbolo e uma foto identificada.','Qual componente realiza a manobra frequente do motor?','Contator|Sinalizador|Botoeira',0],
['Leitura de circuito de comando',0,'Uma esteira só funciona enquanto o operador mantém a botoeira pressionada.','Circuito: S0 NF e FR NF em série; S1 NA em paralelo com auxiliar KM NA; bobina KM ao final. O auxiliar KM está desconectado.','Descreva o caminho da corrente ao pressionar S1 e após soltá-lo; explique o selo e a causa da parada. Use a simulação de partida direta.','Diagrama comentado e sequência ligar, manter e parar.','Qual contato mantém a bobina energizada após soltar S1?','Auxiliar KM NA|S0 NF|FR NF',0],
['Partida direta',1,'Uma bomba de bancada deve operar por comando de três fios.','Motor fictício: 2,2 kW no eixo, 220/380 V Δ/Y, rede 220 V trifásica, η = 0,85, FP = 0,80. Comando 24 Vcc.','Estime a corrente; justifique a ligação do motor; desenhe potência e comando com selo; planeje testes supervisionados de partida e parada.','Cálculo rastreável, dois diagramas e registro da montagem supervisionada ou simulação identificada.','Na rede 220 V, qual ligação corresponde à placa informada?','Triângulo|Estrela|Qualquer ligação',0],
['Reversão de motores',1,'Uma esteira precisa deslocar peças nos dois sentidos, sempre parando antes da reversão.','Motor 220/380 V Δ/Y, rede 220 V. KM1 sentido A; KM2 sentido B. Comando 24 Vcc. Considere reversão somente após parada.','Desenhe a troca de duas fases; inclua intertravamento elétrico cruzado e mecânico; explique o risco de sobreposição e registre testes da simulação.','Diagramas e tabela de estados KM1/KM2 com testes de comandos conflitantes.','Qual estado é incompatível?','KM1 e KM2 ligados|Ambos desligados|Somente KM1 ligado',0],
['Estrela-triângulo',1,'Um ventilador com partida a vazio exige análise de redução de corrente.','Rede 380 V; motor 380/660 V Δ/Y, seis terminais; corrente em partida direta Δ = 90 A. Sequência didática: estrela 5 s, intervalo aberto 1 s, triângulo.','Verifique a compatibilidade; estime corrente de linha em estrela e torque relativo; explique a transição aberta e compare com um motor 220/380 V.','Cálculos, diagrama de sequência e justificativa da compatibilidade.','Qual corrente idealizada em estrela?','30 A|52 A|90 A',0],
['Partida compensada',1,'Uma bomba deve partir com tensão reduzida por autotransformador.','Rede 380 V; corrente de partida direta = 120 A; torque direto = 100 N·m. Compare k = 0,50; 0,65; 0,80.','Calcule tensão, corrente no motor, corrente na rede e torque para cada k; discuta se uma carga exigindo 50 N·m consegue acelerar em cada caso idealizado.','Tabela comparativa com fórmulas e limites do modelo.','Com k = 0,80, a corrente de rede representa quanto da direta?','64%|80%|40%',0],
['Seleção de componentes',3,'Uma bancada precisa de seleção documentada dos componentes de partida direta.','Motor fictício: 7,5 kW, 380 V, corrente de placa 15,5 A, serviço S1, 6 partidas/h, ambiente 40 °C, comando 24 Vcc. Corrente de curto-circuito do local: pendente.','Consulte catálogo oficial; justifique contator por categoria e corrente; relé pela faixa e posição; proteção por coordenação e capacidade de interrupção. Liste dados faltantes.','Tabela de candidatos com referência, página, edição e pendências; não aprovar seleção final com dados faltantes.','Qual informação é essencial à capacidade de interrupção?','Curto-circuito presumido|Cor do painel|Comprimento da etiqueta',0],
['Soft-starter',2,'Uma bomba apresenta trancos na partida e requer um estudo de acionamento suave.','Motor 5,5 kW, 380 V, 11,5 A de placa. Simulação conceitual: rampa 10 s e limite inicial 3 × In; valores são hipóteses de estudo. Modelo real ainda não escolhido.','Compare rampa de tensão e limitação de corrente; discuta carga, aquecimento, partidas/h e bypass; prepare plano de ajuste baseado no manual escolhido.','Roteiro com parâmetros por função (sem inventar códigos), critérios de teste e fonte.','Uma soft-starter convencional controla continuamente a frequência?','Não|Sim|Somente com bypass',0],
['Inversor em modo local',2,'Uma bancada será comissionada com referência pelo teclado do inversor.','Motor fictício 1,5 kW, 220 V Δ, 6 A, 60 Hz, 1720 rpm; inversor deve ser compatível. Marca, modelo e firmware devem ser confirmados antes de parametrizar.','Registre placa; localize no manual seleção de comando local, referência, dados de motor e limites; proponha testes supervisionados a baixa referência adequada à carga.','Roteiro com função, código validado no manual, valor proposto, página e resultado esperado.','Os códigos de parâmetros podem ser transferidos entre modelos sem conferir?','Não|Sim|Somente se a potência for igual',0],
['Inversor em modo remoto',2,'Uma esteira será comandada por entradas digitais e potenciômetro.','Motor 1,5 kW, 220 V. Referência didática 0–10 V → 0–60 Hz. Entrada digital de marcha e entrada de parada conforme lógica do manual a selecionar.','Calcule referência para 5 V; planeje sinais, comum, blindagem e lógica PNP/NPN conforme manual; explique o diagnóstico de referência ignorada.','Diagrama de sinais e tabela de funções com validação pendente dos terminais reais.','Na escala linear dada, 5 V corresponde a:','30 Hz|5 Hz|60 Hz',0],
['Diagnóstico de falhas',3,'Uma linha fictícia apresenta ausência de partida e referência de velocidade ignorada.','Caso A: comando 24 Vcc presente, FR atuado, bobina sem tensão. Caso B: inversor sem falha, comando local ativo, referência remota em 5 V não altera a velocidade.','Construa hipóteses, evidências e testes seguros; diferencie causa e sintoma; proponha correções e verificações sem neutralizar proteções.','Árvore de diagnóstico para ambos os casos e registro de conclusão.','Após atuação de sobrecarga, a primeira atitude adequada é:','Investigar a causa|Neutralizar FR|Rearmar repetidamente',0],
['Projeto integrador',3,'Uma equipe deve propor o acionamento de uma esteira de separação.','Motor fictício 3 kW, 220/380 V Δ/Y, 60 Hz, 4 polos, η = 0,87, FP = 0,82; rede 380 V; operação com velocidade variável. Carga e curto-circuito requerem levantamento.','Compare partida direta, soft-starter e inversor; estime corrente e velocidade síncrona; proponha arquitetura, diagramas, seleção preliminar e plano de comissionamento.','Memorial técnico, cálculos, diagramas, lista de componentes com fontes, plano de testes e contribuição individual.','Qual solução permite variar frequência de alimentação?','Inversor de frequência|Contator|Autotransformador fixo',0]
];
export const activities=raw.map((r,i)=>({id:String(i+1),code:`AEI-${String(i+1).padStart(2,'0')}`,title:r[0] as string,track:r[1] as number,context:r[2] as string,data:r[3] as string,steps:r[4] as string,evidence:r[5] as string,question:r[6] as string,options:(r[7] as string).split('|'),answer:r[8] as number,objectives:'Interpretar o problema, justificar decisões técnicas e documentar as verificações propostas.',prerequisites:i<2?'Noções de eletricidade e orientação inicial de segurança.':'Fundamentos de circuitos de potência e comando; atividades anteriores da trilha.',resources:'Computador, caderno, simulador, catálogos oficiais e bancada somente sob supervisão.',safety:'Intervenções reais dependem de supervisão, infraestrutura e procedimentos institucionais. Planeje o trabalho desenergizado; nunca neutralize proteções.',minutes:i===11?180: i<2?40:60,mode:i===11?'Trio':i<2?'Individual':'Dupla',difficulty:i<2?'Inicial':i>9?'Avançada':'Intermediária',due:`2026-10-${String(5+i).padStart(2,'0')}`,published:true,archived:false,version:1,points:10,classId:'t1',rubric:criteria.map((name,j)=>({name,weight:j===7?1:2})),release:false}));
export function seed(){return {schema:1,activities,classes:[{id:'t1',name:'Eletrotécnica · Turma 2026',hours:80}],students:[{id:'s1',name:'Marina Costa (fictícia)',classId:'t1'},{id:'s2',name:'Lucas Almeida (fictício)',classId:'t1'},{id:'s3',name:'Rafael Lima (fictício)',classId:'t1'}],teams:[{id:'e1',name:'Equipe 01',classId:'t1',members:['s1','s2']}],submissions:{} as Record<string,any>,logo:'',teacher:'Joelson Moreira Mendes'};}
